### ISSUE TITLE
Javascript ES6?

### ISSUE THREAD

**Issue by segg21** [Yaro70/Codiad-YS-Outline#1]
That's a must :)

**Comment by yaro90** [comment]
Maybe at some point in the future, if I get time...
However there is nothing stopping you from writing a javascript mode yourself and creating a PR ;)

**Comment by segg21** [comment]
@Yaro70 haha, yea, you're right. I'll take a look.

**Comment by segg21** [comment]
@Yaro70 Hey again. I finally discovered that I opened this issue in the past. Forgot to take actions.

I went to go look at the modes and the one thing that is preventing me from doing so myself is the Regex. 

I gave up trying to fully learn Regex. Because with Regex, it's different for many languages, and overall just had a hard time working with it in the past.

So, technically that's stopping me :/

But consider/implement ES6 at your own will/pace. I no longer use Codiad. At one point for collaboration, but it didn't work out as planned.
